# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GithubCI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_FB_API_KEY: ${{ secrets.REACT_APP_FB_API_KEY }}
      REACT_APP_FB_APP_IP: ${{ secrets.REACT_APP_FB_APP_IP }}
      REACT_APP_FB_AUTH_DOMAIN: ${{ secrets.REACT_APP_FB_AUTH_DOMAIN }}
      REACT_APP_FB_DB_URL: ${{ secrets.REACT_APP_FB_DB_URL }}
      REACT_APP_FB_MEASUREMENT_ID: ${{ secrets.REACT_APP_FB_MEASUREMENT_ID }}
      REACT_APP_FB_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FB_MESSAGING_SENDER_ID }}
      REACT_APP_FB_PROJECT_ID: ${{ secrets.REACT_APP_FB_PROJECT_ID }}
      REACT_APP_FB_STORAGE_BUCKET: ${{ secrets.REACT_APP_FB_STORAGE_BUCKET }}
      REACT_APP_NOT_SECRET_CODE: ${{ secrets.REACT_APP_NOT_SECRET_CODE }}
      REACT_APP_SB_APP_ID: ${{ secrets.REACT_APP_SB_APP_ID }}
      REACT_APP_ST_DSN: ${{ secrets.REACT_APP_ST_DSN }}

    #     strategy:
    #       matrix:
    #         node-version: [10.x, 12.x, 14.x]

    #     steps:
    #     - uses: actions/checkout@v2
    #     - name: Use Node.js ${{ matrix.node-version }}
    #       uses: actions/setup-node@v1
    #       with:
    #         node-version: ${{ matrix.node-version }}
    #     - run: npm ci
    #     - run: npm run build --if-present
    #     - run: npm test

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm test

      - name: Build
        run: npm run build
